server:
  port: 8087
spring:
  freemarker:
    template-loader-path: classpath:/web/
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
  redis:
    port: 6379
    pool:
      max-idle:20
      min-idle:1
      max-active:20
      max-wait:60000
    database: 0
    host: 127.0.0.1


